# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/prettier/prettier
    rev: 1.19.1 # Use the sha or tag you want to point at
    hooks:
    -   id: prettier
        name: prettier
        files: \.(js|vue)$
